-- =====================================================
-- Script SQL: Tabla PROCESOS_SINCRONIZACION
-- Propósito: Gestionar qué procesos están implementados y activos para sincronización batch
-- =====================================================

-- Crear tabla para procesos de sincronización
CREATE TABLE PROCESOS_SINCRONIZACION (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PROCESS_TYPE VARCHAR2(50) NOT NULL UNIQUE,
    ESTA_IMPLEMENTADO NUMBER(1) DEFAULT 0 NOT NULL, -- 0=No implementado, 1=Implementado
    ACTIVO NUMBER(1) DEFAULT 1 NOT NULL, -- 0=Inactivo, 1=Activo
    DESCRIPCION VARCHAR2(200),
    FECHA_INSERCION DATE DEFAULT SYSDATE NOT NULL,
    FECHA_ACTUALIZACION DATE,
    USUARIO_INSERTO VARCHAR2(100),
    ULTIMO_USUARIO_ACTUALIZO VARCHAR2(100),
    CONSTRAINT CHK_IMPLEMENTADO CHECK (ESTA_IMPLEMENTADO IN (0, 1)),
    CONSTRAINT CHK_ACTIVO CHECK (ACTIVO IN (0, 1))
);

-- Comentarios en la tabla
COMMENT ON TABLE PROCESOS_SINCRONIZACION IS 'Tabla para gestionar procesos de sincronización batch implementados y activos';
COMMENT ON COLUMN PROCESOS_SINCRONIZACION.ID IS 'Identificador único del registro';
COMMENT ON COLUMN PROCESOS_SINCRONIZACION.PROCESS_TYPE IS 'Tipo de proceso (debe coincidir con el enum ProcessType en código)';
COMMENT ON COLUMN PROCESOS_SINCRONIZACION.ESTA_IMPLEMENTADO IS 'Indica si el proceso está completamente implementado (1=Sí, 0=No)';
COMMENT ON COLUMN PROCESOS_SINCRONIZACION.ACTIVO IS 'Indica si el proceso está activo y puede ejecutarse (1=Activo, 0=Inactivo)';
COMMENT ON COLUMN PROCESOS_SINCRONIZACION.DESCRIPCION IS 'Descripción del proceso';
COMMENT ON COLUMN PROCESOS_SINCRONIZACION.FECHA_INSERCION IS 'Fecha y hora de creación del registro';
COMMENT ON COLUMN PROCESOS_SINCRONIZACION.FECHA_ACTUALIZACION IS 'Fecha y hora de última actualización';
COMMENT ON COLUMN PROCESOS_SINCRONIZACION.USUARIO_INSERTO IS 'Usuario que creó el registro';
COMMENT ON COLUMN PROCESOS_SINCRONIZACION.ULTIMO_USUARIO_ACTUALIZO IS 'Último usuario que actualizó el registro';

-- Crear índice único en PROCESS_TYPE
CREATE UNIQUE INDEX IDX_PROCESS_TYPE ON PROCESOS_SINCRONIZACION(PROCESS_TYPE);

-- Crear índice para búsquedas por estado
CREATE INDEX IDX_ESTA_IMPLEMENTADO ON PROCESOS_SINCRONIZACION(ESTA_IMPLEMENTADO, ACTIVO);

-- Insertar proceso inicial (ProductList)
INSERT INTO PROCESOS_SINCRONIZACION (
    PROCESS_TYPE,
    ESTA_IMPLEMENTADO,
    ACTIVO,
    DESCRIPCION,
    USUARIO_INSERTO
) VALUES (
    'ProductList',
    1, -- Implementado
    1, -- Activo
    'Sincronización de lista de productos',
    'SYSTEM'
);

COMMIT;

-- Query para consultar procesos implementados y activos
-- SELECT PROCESS_TYPE, DESCRIPCION, ESTA_IMPLEMENTADO, ACTIVO
-- FROM PROCESOS_SINCRONIZACION
-- WHERE ESTA_IMPLEMENTADO = 1 AND ACTIVO = 1
-- ORDER BY PROCESS_TYPE;

-- Query para agregar un nuevo proceso (cuando esté implementado)
-- INSERT INTO PROCESOS_SINCRONIZACION (
--     PROCESS_TYPE,
--     ESTA_IMPLEMENTADO,
--     ACTIVO,
--     DESCRIPCION,
--     USUARIO_INSERTO
-- ) VALUES (
--     'PriceList',
--     1, -- Implementado
--     1, -- Activo
--     'Sincronización de lista de precios',
--     'USUARIO_ACTUAL'
-- );

-- Query para desactivar un proceso temporalmente (sin eliminarlo)
-- UPDATE PROCESOS_SINCRONIZACION
-- SET ACTIVO = 0,
--     FECHA_ACTUALIZACION = SYSDATE,
--     ULTIMO_USUARIO_ACTUALIZO = 'USUARIO_ACTUAL'
-- WHERE PROCESS_TYPE = 'ProductList';

-- =====================================================
-- FIN DEL SCRIPT
-- =====================================================

